

import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JLabel;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;





/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class LOGIN extends javax.swing.JFrame {
    public static String mail_Id;

    /**
     * Creates new form LOGIN
     */
    /* private void makeFrameFullSize(JFrame aFrame) {
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    aFrame.setSize(screenSize.width, screenSize.height);
}
   */
    public static String getMail(){
        return mail_Id;
    }
    public LOGIN() {
        initComponents();
        JLabel j1=new JLabel();
        this.setSize(1915, 1907);
        
        
        
       
        
        /*this.Undecorated(true);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        Toolkit tk=Toolkit.getDefaultToolkit();
               int xsize=(int) tk.getScreenSize().getWidth();
               int ysize=(int)tk.getScreenSize().getHeight();
        this.setSize(xsize,ysize);
               
        
        
        //getContentPane().setBackground(Color.green);
       // setContentPane(new JLabel(new ImageIcon("F:\sharadhi\pngtree-3d-realistic-vector-background-retro-lightbox-billboard-for-cine-png-image_946223.jpg")));
        /*setTitle("Background Color for JFrame");
        setSize(400,400);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);
        setLayout(new BorderLayout());
        setContentPane(new JLabel(new ImageIcon("C:\\Users\\Computer\\Downloads\\colorful design.png")));
        setLayout(new FlowLayout());
        l1=new JLabel();
        l2=new JLabel();
        b1=new JButton();
        b2=new JButton();
        add(l1);
        add(b1);
        add(l2);
        add(b2);*
        
        // Just for refresh :) Not optional!
        setSize(399,399);
        setSize(400,400);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JPasswordField();
        j1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setBackground(new java.awt.Color(255, 153, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        l1.setFont(new java.awt.Font("Brush Script MT", 2, 48)); // NOI18N
        l1.setForeground(new java.awt.Color(204, 204, 255));
        l1.setText("Username");
        getContentPane().add(l1);
        l1.setBounds(560, 470, 210, 60);

        l2.setFont(new java.awt.Font("Brush Script MT", 2, 48)); // NOI18N
        l2.setForeground(new java.awt.Color(204, 204, 255));
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setText("Password");
        getContentPane().add(l2);
        l2.setBounds(530, 580, 210, 50);

        b1.setBackground(new java.awt.Color(0, 204, 51));
        b1.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        b1.setForeground(new java.awt.Color(51, 51, 51));
        b1.setText("LOGIN");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(600, 690, 210, 60);

        b2.setBackground(new java.awt.Color(0, 204, 51));
        b2.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        b2.setForeground(new java.awt.Color(51, 51, 51));
        b2.setText("SIGN UP");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(950, 690, 220, 60);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(990, 480, 220, 40);

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2);
        t2.setBounds(990, 580, 220, 40);

        j1.setBackground(new java.awt.Color(204, 255, 204));
        j1.setIcon(new javax.swing.ImageIcon("F:\\sharadhi\\download.png")); // NOI18N
        getContentPane().add(j1);
        j1.setBounds(-50, -390, 1920, 1910);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
SIGNUP s=new SIGNUP();
s.setVisible(true);


    }//GEN-LAST:event_b2ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
// TODO add your handling code here:
        String nam=t1.getText();
        String pas=t2.getText();
        int flag=0;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/moviebooking", "root", "");
            Statement s=c.createStatement();
            ResultSet r=s.executeQuery("select * from user_information");
            while(r.next())
            {
                if(nam.equals(r.getString(1))&&pas.equals(r.getString(3)))
                {   mail_Id=r.getString(2);
                    flag=1;
                    new HOMEPAGE().setVisible(true);
                }
            }
            if(flag==0)
            {
                JOptionPane.showMessageDialog(null,"Invalid password or username");
            }
                       
            
        }
        catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_b1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    /**
     * @param args the command line arguments
     */
  
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       /*  JFrame frame=new JFrame("My Frame");
         frame.setExtendedState(frame.getExtendedState()|JFrame.MAXIMIZED_BOTH);
         
         /*JLabel j1=new JLabel();
         int xsize=myFrame.getHeight();
         int ysize=myFrame.getWidth();
         j1.setSize(xsize,ysize);
         */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new LOGIN().setVisible(true);
            }
        
       
         });
         
        
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JLabel j1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JTextField t1;
    private javax.swing.JPasswordField t2;
    // End of variables declaration//GEN-END:variables

    
}
