
import java.sql.*;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class SHOW_TIMING extends javax.swing.JFrame {
    static String show_time;
    static String movie2;
    static String theatre;
    static int show_id;

    
   public static String getShowTime(){
       return(show_time);
       
   }
   public  String getTheatre(){
       return(theatre);
   }
   public static int getShowId(){
      return show_id;
  }
   
       
      /*if((CHOICE.getMovieName().equals("KGF"))&&(show_time.equals("9:00AM")))
          show_id=1;
     
      else if((CHOICE.getMovieName().equals("KGF"))&&(show_time.equals("12:00PM")))
          show_id=2;
      else if((CHOICE.getMovieName().equals("KGF"))&&(show_time.equals("5:00PM")))
          show_id=3;
      else if((CHOICE.getMovieName().equals("AVENGERS"))&&(show_time.equals("9:00AM")))
          show_id=4;
      else if((CHOICE.getMovieName().equals("AVENGERS"))&&(show_time.equals("12:00PM")))
          show_id=5;
      else if((CHOICE.getMovieName().equals("AVENGERS"))&&(show_time.equals("5:00PM")))
          show_id=6;
      else if((CHOICE.getMovieName().equals("TANGLED"))&&(show_time.equals("9:00AM")))
          show_id=7;
      else if((CHOICE.getMovieName().equals("TANGLED"))&&(show_time.equals("12:00PM")))
          show_id=8;
      else if((CHOICE.getMovieName().equals("TANGLED"))&&(show_time.equals("5:00PM")))
          show_id=9;
       return show_id;
   }*/

       

   
    /**
     * Creates new form SHOW_TIMING
     */
    public SHOW_TIMING() {
        initComponents();
        this.setSize(1868, 1447);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TIMING");
        getContentPane().setLayout(null);

        jComboBox1.setBackground(new java.awt.Color(0, 204, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "9:00AM", "12:00PM", "5:00PM" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(920, 180, 340, 30);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Please select your show timing");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(490, 170, 340, 50);

        jButton1.setBackground(new java.awt.Color(204, 0, 51));
        jButton1.setText("DONE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(770, 390, 230, 60);

        jButton2.setBackground(new java.awt.Color(204, 0, 51));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(770, 510, 230, 60);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Choose Your Nearest Theatre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(490, 250, 330, 40);

        jComboBox2.setBackground(new java.awt.Color(0, 204, 204));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PVR", "CINEPOLIS", "BIG CINEMA" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(920, 260, 340, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("F:\\sharadhi\\cinema.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, -10, 1980, 1500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
         show_time=jComboBox1.getSelectedItem().toString();
          
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       SEATS S=new SEATS();
       S.setVisible(true); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().equals(null)|jComboBox2.getSelectedItem().equals(null))
        {
                     JOptionPane.showMessageDialog(null,"Please select one among these option");

        }
        theatre=jComboBox2.getSelectedItem().toString();
        
        try{
         CHOICE C=new CHOICE();
         String movie=C.getMovieName();
            Class.forName("com.mysql.jdbc.Driver");
         Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/moviebooking", "root", "");
         Statement s=c.createStatement();
         ResultSet r=s.executeQuery("select * from shows");
         while(r.next()){
           if(r.getString(2).equals(show_time)&&r.getString(4).equals(movie)){
                 show_id=r.getInt(1);
                 
             }
         }
        }
        catch(Exception e){
                            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
        CHOICE C=new CHOICE();
        C.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SHOW_TIMING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SHOW_TIMING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SHOW_TIMING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SHOW_TIMING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SHOW_TIMING().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
